### ISSUE TITLE
Add Support Versions in the Security Policy

### ISSUE THREAD

**Issue by waynejohnn** [Intelius/automated-data-pipelines#11]
Add Support Versions in the Security Policy Page.

**Comment by rezaghaffari** [comment]
I am not sure that I understand the purpose of "the supported versions" in the Security Policy. Example below suggests that we tell people in which versions of this project, we are supporting security updates:
[https://github.com/danpoynor/special-github-files/blob/main/SECURITY.md](https://github.com/danpoynor/special-github-files/blob/main/SECURITY.md)
If we want to follow this template, we can specify that our future release 1.0 supports security updates.
If it is better to list the main components of this project, here is the list but I am not sure what should I specify under "supported" column:

| Package                                | Version | Supported          |
| -------------------------------------- | ------- | ------------------ |
| Apache Airflow                         | 2.1.4   | :white_check_mark: |
| Apache Kafka (packaged by Bitnami)     | 3.1.0   | :white_check_mark: |
| MySQL (packaged by Bitnami)            | 8.0.27  | :white_check_mark: |
| FastAPI                                | 0.75.2  | :white_check_mark: |

@waynejohnn
